<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Vlad Tomutiu">
<meta name="author" content="DS303, SP26">
<meta name="author" content="Prof.&nbsp;Amber Camp">
<meta name="dcterms.date" content="2026-03-12">

<title>Assignment 2: Wrapping up regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="assignment02-regression-wrapup_files/libs/clipboard/clipboard.min.js"></script>
<script src="assignment02-regression-wrapup_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="assignment02-regression-wrapup_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="assignment02-regression-wrapup_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="assignment02-regression-wrapup_files/libs/quarto-html/popper.min.js"></script>
<script src="assignment02-regression-wrapup_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="assignment02-regression-wrapup_files/libs/quarto-html/anchor.min.js"></script>
<link href="assignment02-regression-wrapup_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="assignment02-regression-wrapup_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="assignment02-regression-wrapup_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="assignment02-regression-wrapup_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="assignment02-regression-wrapup_files/libs/bootstrap/bootstrap-e261b86ae15e22bf333780d8a72f25c9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#wrapping-up-linear-and-logistic-regression" id="toc-wrapping-up-linear-and-logistic-regression" class="nav-link active" data-scroll-target="#wrapping-up-linear-and-logistic-regression">Wrapping up linear and logistic regression<sup>*</sup></a>
  <ul class="collapse">
  <li><a href="#load-packages" id="toc-load-packages" class="nav-link" data-scroll-target="#load-packages">Load Packages</a></li>
  <li><a href="#load-data" id="toc-load-data" class="nav-link" data-scroll-target="#load-data">Load Data</a></li>
  <li><a href="#question-1-describe-the-data" id="toc-question-1-describe-the-data" class="nav-link" data-scroll-target="#question-1-describe-the-data">Question 1: Describe the data</a></li>
  <li><a href="#question-2-eda" id="toc-question-2-eda" class="nav-link" data-scroll-target="#question-2-eda">Question 2: EDA</a></li>
  <li><a href="#question-3-apply-a-linear-regression" id="toc-question-3-apply-a-linear-regression" class="nav-link" data-scroll-target="#question-3-apply-a-linear-regression">Question 3: Apply a linear regression</a></li>
  <li><a href="#question-4-apply-a-multiple-linear-regression" id="toc-question-4-apply-a-multiple-linear-regression" class="nav-link" data-scroll-target="#question-4-apply-a-multiple-linear-regression">Question 4: Apply a multiple linear regression</a></li>
  <li><a href="#question-5-include-an-interaction" id="toc-question-5-include-an-interaction" class="nav-link" data-scroll-target="#question-5-include-an-interaction">Question 5: Include an interaction</a></li>
  <li><a href="#question-6-compare-models" id="toc-question-6-compare-models" class="nav-link" data-scroll-target="#question-6-compare-models">Question 6: Compare models</a></li>
  <li><a href="#question-7-categorical-predictors" id="toc-question-7-categorical-predictors" class="nav-link" data-scroll-target="#question-7-categorical-predictors">Question 7: Categorical predictors</a></li>
  <li><a href="#question-8-relevel-your-categorical-variable" id="toc-question-8-relevel-your-categorical-variable" class="nav-link" data-scroll-target="#question-8-relevel-your-categorical-variable">Question 8: Relevel your categorical variable</a></li>
  <li><a href="#question-9-fit-a-logistic-regression" id="toc-question-9-fit-a-logistic-regression" class="nav-link" data-scroll-target="#question-9-fit-a-logistic-regression">Question 9: Fit a logistic regression</a></li>
  <li><a href="#question-10-synthesize-the-information" id="toc-question-10-synthesize-the-information" class="nav-link" data-scroll-target="#question-10-synthesize-the-information">Question 10: Synthesize the information</a></li>
  <li><a href="#bonus-stepwise-regression" id="toc-bonus-stepwise-regression" class="nav-link" data-scroll-target="#bonus-stepwise-regression">Bonus: Stepwise Regression</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assignment 2: Wrapping up regression</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Vlad Tomutiu </p>
             <p>DS303, SP26 </p>
             <p>Prof.&nbsp;Amber Camp </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 12, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="wrapping-up-linear-and-logistic-regression" class="level1">
<h1>Wrapping up linear and logistic regression<sup>*</sup></h1>
<p>Assignment 2 covers linear and logistic regression models and includes many of the topics we have covered over the entire semester. You will be using <code>palmerpenguins</code> data, which includes a nice variety of continuous and categorical predictors.</p>
<p>To submit this assignment, render this file and save as a pdf. Commit &amp; push this qmd to GitHub and upload the pdf to Canvas.</p>
<p>*This assignment does not include mixed effects models, but you will be seeing that on another assignment.</p>
<section id="load-packages" class="level2">
<h2 class="anchored" data-anchor-id="load-packages">Load Packages</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("palmerpenguins") # install if needed</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="load-data" class="level2">
<h2 class="anchored" data-anchor-id="load-data">Load Data</h2>
<p>Load the <code>penguins</code> data and examine it below (use <code>summary()</code>, etc.)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="ot">&lt;-</span> penguins</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(penguins)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      species          island    bill_length_mm  bill_depth_mm  
 Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
 Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
 Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
                                 Mean   :43.92   Mean   :17.15  
                                 3rd Qu.:48.50   3rd Qu.:18.70  
                                 Max.   :59.60   Max.   :21.50  
                                 NA's   :2       NA's   :2      
 flipper_length_mm  body_mass_g       sex           year     
 Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
 1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
 Median :197.0     Median :4050   NA's  : 11   Median :2008  
 Mean   :200.9     Mean   :4202                Mean   :2008  
 3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
 Max.   :231.0     Max.   :6300                Max.   :2009  
 NA's   :2         NA's   :2                                 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>??penguins</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>starting httpd help server ... done</code></pre>
</div>
</div>
</section>
<section id="question-1-describe-the-data" class="level2">
<h2 class="anchored" data-anchor-id="question-1-describe-the-data">Question 1: Describe the data</h2>
<p>What information is contained in this data set? Describe at least four variables (excluding <code>year</code>), including what they represent and their data type. Lastly, describe whether you think <code>year</code> would be a useful predictor in this data.</p>
<p><strong>Answer</strong>:<br>
species - the type of penguin that is used in the data (Adelie, Chinstrap, and Gentoo), the data type is factor.</p>
<p>sex - Whether the penguin is a male or female, the data type is also factor.</p>
<p>body-mass_g - An integer of the body mass of the penguins in grams, the data type is integer.</p>
<p>island - the type of island that the penguins are from (Biscoe, Dream, or Torgersen), the data type is factor.</p>
<p>I think year would be a useful predictor for this data because different years have different events, causing changes to specific things that can be measured in the penguins data, for example a warmer year might mean less of a certain penguin on an island. This is why I think year could be a specific predictor in this data.</p>
</section>
<section id="question-2-eda" class="level2">
<h2 class="anchored" data-anchor-id="question-2-eda">Question 2: EDA</h2>
<p>Explore your data visually. Create at least two visualizations that show the relationship between <code>flipper_length_mm</code> and its potential predictors.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(<span class="at">x =</span> flipper_length_mm, <span class="at">y =</span> bill_length_mm, <span class="at">color =</span> species)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment02-regression-wrapup_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(<span class="at">x =</span> flipper_length_mm, <span class="at">y =</span> body_mass_g, <span class="at">color =</span> species)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment02-regression-wrapup_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(<span class="at">x =</span> flipper_length_mm, <span class="at">y =</span> island, <span class="at">color =</span> species)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment02-regression-wrapup_files/figure-html/unnamed-chunk-3-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(<span class="at">x =</span> flipper_length_mm, <span class="at">y =</span> species, <span class="at">color =</span> species)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment02-regression-wrapup_files/figure-html/unnamed-chunk-3-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(<span class="at">x =</span> flipper_length_mm, <span class="at">y =</span> bill_depth_mm, <span class="at">color =</span> species)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment02-regression-wrapup_files/figure-html/unnamed-chunk-3-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(<span class="at">x =</span> flipper_length_mm, <span class="at">y =</span> sex, <span class="at">color =</span> species)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment02-regression-wrapup_files/figure-html/unnamed-chunk-3-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(<span class="at">x =</span> flipper_length_mm, <span class="at">y =</span> year, <span class="at">color =</span> species)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment02-regression-wrapup_files/figure-html/unnamed-chunk-3-7.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="question-3-apply-a-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="question-3-apply-a-linear-regression">Question 3: Apply a linear regression</h2>
<p>Fit a simple linear regression model predicting <code>flipper_length_mm</code> from <code>body_mass_g</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>penguins_f_bm <span class="ot">&lt;-</span> <span class="fu">lm</span>(flipper_length_mm <span class="sc">~</span> body_mass_g, <span class="at">data =</span> penguins)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(penguins_f_bm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = flipper_length_mm ~ body_mass_g, data = penguins)

Residuals:
     Min       1Q   Median       3Q      Max 
-23.7626  -4.9138   0.9891   5.1166  16.6392 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 1.367e+02  1.997e+00   68.47   &lt;2e-16 ***
body_mass_g 1.528e-02  4.668e-04   32.72   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.913 on 340 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.759, Adjusted R-squared:  0.7583 
F-statistic:  1071 on 1 and 340 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Interpret your model output, including the intercept and slope, in your own words below. Be sure to include a sentence explaining how <code>body_mass_g</code> impacts <code>flipper_length_mm</code> and whether or not the effect is significant.</p>
<p><strong>Answer:</strong><br>
Intercept (136.7) - When body mass is 0 grams, then the flipper length in mm is 136.7</p>
<p>slope (152.8) - For every one unit increase in body mass, flipper length increases by approximately 0.01528 grams and it is statistically significant.</p>
</section>
<section id="question-4-apply-a-multiple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="question-4-apply-a-multiple-linear-regression">Question 4: Apply a multiple linear regression</h2>
<p>Fit a linear regression model predicting <code>flipper_length_mm</code> from both <code>body_mass_g</code> and <code>bill_length_mm</code>. Interpret the slopes and intercept.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>penguins_fl <span class="ot">&lt;-</span> <span class="fu">lm</span>(flipper_length_mm <span class="sc">~</span> body_mass_g <span class="sc">+</span> bill_length_mm, <span class="at">data =</span> penguins)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(penguins_fl)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = flipper_length_mm ~ body_mass_g + bill_length_mm, 
    data = penguins)

Residuals:
     Min       1Q   Median       3Q      Max 
-21.0989  -4.5520   0.3379   4.8942  16.0953 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    1.220e+02  2.855e+00  42.715  &lt; 2e-16 ***
body_mass_g    1.305e-02  5.452e-04  23.939  &lt; 2e-16 ***
bill_length_mm 5.492e-01  8.008e-02   6.859 3.31e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.488 on 339 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.7884,    Adjusted R-squared:  0.7871 
F-statistic: 631.4 on 2 and 339 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Similar to Question 3, interpret the model output in your own words here:</p>
<p><strong>Answer:</strong><br>
Intercept (122.0) - When body mass is 0 grams and bill length is 0 millimeters, then the flipper length in millimeters is 122.0.</p>
<p>the coefficient for body_mass_g is 0.01305, indicating that for every one unit increase in body mass, flipper length increases by approximately 0.01305 grams and it is statistically significant.</p>
<p>the coefficient for bill_length_mm is 0.5492, indicating that for every one unit increase in body mass, flipper length increases by approximately 0.5492 millimeters and it is statistically significant.</p>
</section>
<section id="question-5-include-an-interaction" class="level2">
<h2 class="anchored" data-anchor-id="question-5-include-an-interaction">Question 5: Include an interaction</h2>
<p>Fit a linear regression model predicting <code>flipper_length_mm</code> from <code>body_mass_g,</code> <code>bill_length_mm</code>, and the <strong>interaction</strong> of the two. Interpret the slopes and intercept.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>interaction <span class="ot">&lt;-</span> <span class="fu">lm</span>(flipper_length_mm <span class="sc">~</span> body_mass_g <span class="sc">+</span> bill_length_mm <span class="sc">+</span> body_mass_g<span class="sc">:</span>bill_length_mm, <span class="at">data =</span> penguins)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(interaction)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = flipper_length_mm ~ body_mass_g + bill_length_mm + 
    body_mass_g:bill_length_mm, data = penguins)

Residuals:
     Min       1Q   Median       3Q      Max 
-20.0160  -4.2070   0.3699   5.0793  16.6926 

Coefficients:
                             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                 1.706e+02  1.612e+01  10.587  &lt; 2e-16 ***
body_mass_g                 4.364e-04  4.149e-03   0.105  0.91629    
bill_length_mm             -5.051e-01  3.528e-01  -1.432  0.15315    
body_mass_g:bill_length_mm  2.707e-04  8.827e-05   3.066  0.00234 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.409 on 338 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.7941,    Adjusted R-squared:  0.7923 
F-statistic: 434.5 on 3 and 338 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Interpret the model output in your own words below. If there was a change in the pattern of significance, try to explain the logic below as well.</p>
<p><strong>Answer:</strong></p>
<p>Intercept (170.6) - The flipper length in millimeters is 170.6 when all other variables are zero.</p>
<p>the coefficient for body_mass_g is 4.364e-04, indicating that for every one unit increase in body mass, flipper length increases by approximately 4.364e-04 grams and it is no longer statistically significant.</p>
<p>the coefficient for bill_length_mm is -5.051e-01, indicating that for every one unit increase in body mass, flipper length decreases by approximately -5.051e-01 millimeters and it is also no longer statistically significant.</p>
<p>The coefficient for body_mass_g:bill_length_mm is 2.707e-04, indicating that when body_mass_g increases by one unit, the effect of body_mass_g on bill_length_mm increases by 2.707e-04.</p>
<p>There was a change in the pattern because body_mass_g and bill_length_mm are no longer statistically significant. The interaction between body_mass_g and bill_length_mm becomes much more significant then just the two variables independently, meaning that the interaction becomes statistically significant, while the coefficients of the individual variables decrease and they lose their significance.</p>
</section>
<section id="question-6-compare-models" class="level2">
<h2 class="anchored" data-anchor-id="question-6-compare-models">Question 6: Compare models</h2>
<p>Compare the models you built in Questions 4 and 5 using <code>anova()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(penguins_fl, interaction)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: flipper_length_mm ~ body_mass_g + bill_length_mm
Model 2: flipper_length_mm ~ body_mass_g + bill_length_mm + body_mass_g:bill_length_mm
  Res.Df   RSS Df Sum of Sq     F   Pr(&gt;F)   
1    339 14270                               
2    338 13884  1    386.24 9.403 0.002341 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(penguins_f_bm, interaction)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: flipper_length_mm ~ body_mass_g
Model 2: flipper_length_mm ~ body_mass_g + bill_length_mm + body_mass_g:bill_length_mm
  Res.Df   RSS Df Sum of Sq      F    Pr(&gt;F)    
1    340 16250                                  
2    338 13884  2    2366.4 28.805 2.811e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li><p>Which is the better model? How do you know?</p>
<ul>
<li><strong>Answer:</strong><br>
The interaction model (Question 5) is better because the RSS is lower than the model from question 4.</li>
</ul></li>
<li><p>Is it possible to compare the models from Questions 3 and 5 using the same method? Why or why not?</p>
<ul>
<li><p><strong>Answer:</strong></p>
<p>It is possible to compare the models from Question 3 and 5. As long as models are hierarchical, anova is able to compare the models and help us determine which model is better.<br>
</p></li>
</ul></li>
</ul>
</section>
<section id="question-7-categorical-predictors" class="level2">
<h2 class="anchored" data-anchor-id="question-7-categorical-predictors">Question 7: Categorical predictors</h2>
<p>Build a linear model that includes a categorical predictor of your choice. It is fine to stick with dummy coding. Optional: apply a different coding scheme AND interpret the output correctly for +1 extra credit.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># assign dummy coding</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(penguins<span class="sc">$</span>island)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Dream Torgersen
Biscoe        0         0
Dream         1         0
Torgersen     0         1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># build and summarize your regression</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>dummy <span class="ot">&lt;-</span> <span class="fu">lm</span>(flipper_length_mm <span class="sc">~</span> island, <span class="at">data =</span> penguins)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dummy)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = flipper_length_mm ~ island, data = penguins)

Residuals:
    Min      1Q  Median      3Q     Max 
-37.707  -5.196   1.804   6.927  21.293 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     209.7066     0.8621  243.25   &lt;2e-16 ***
islandDream     -16.6340     1.3207  -12.60   &lt;2e-16 ***
islandTorgersen -18.5105     1.7824  -10.38   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 11.14 on 339 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.376, Adjusted R-squared:  0.3723 
F-statistic: 102.1 on 2 and 339 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p>What is the reference level of your categorical predictor?</p>
<ul>
<li><p><strong>Answer:</strong></p>
<p>The reference level of my categorical predictor is the island Biscoe because it comes first alphabetically.</p></li>
</ul></li>
<li><p>What is your interpretation of this model output? Address all coefficients.</p>
<ul>
<li><p><strong>Answer:</strong></p></li>
<li><p>The average flipper length of the penguins on island Biscoe is 209.7066 millimeters.</p></li>
<li><p>For the change from island Biscoe to island Dream, the flipper length of the penguins decrease by 16.634 millimeters and is statistically significant.</p></li>
<li><p>For the change from island Biscoe to island Torgersen, the flipper length of the penguins decrease by 18.5105 millimeters and is statistically significant.</p></li>
</ul></li>
</ul>
</section>
<section id="question-8-relevel-your-categorical-variable" class="level2">
<h2 class="anchored" data-anchor-id="question-8-relevel-your-categorical-variable">Question 8: Relevel your categorical variable</h2>
<p>Relevel your categorical variable so that a <strong>different</strong> level becomes the reference. Then, run the same model you did in Question 7 and interpret the output.</p>
<p>Relevel:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>penguins<span class="sc">$</span>island <span class="ot">&lt;-</span> <span class="fu">relevel</span>(penguins<span class="sc">$</span>island, <span class="at">ref =</span> <span class="st">"Dream"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Apply same model from Question 7:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>relevel <span class="ot">&lt;-</span> <span class="fu">lm</span>(flipper_length_mm <span class="sc">~</span> island, <span class="at">data =</span> penguins)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(relevel)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = flipper_length_mm ~ island, data = penguins)

Residuals:
    Min      1Q  Median      3Q     Max 
-37.707  -5.196   1.804   6.927  21.293 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      193.073      1.000 192.983   &lt;2e-16 ***
islandBiscoe      16.634      1.321  12.595   &lt;2e-16 ***
islandTorgersen   -1.877      1.853  -1.013    0.312    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 11.14 on 339 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.376, Adjusted R-squared:  0.3723 
F-statistic: 102.1 on 2 and 339 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p>What is the new reference level of your categorical predictor?</p>
<ul>
<li><strong>Answer:</strong></li>
<li>The reference level of my categorical predictor is the island Dream because it comes first alphabetically.</li>
</ul></li>
<li><p>What is your interpretation of this new model output? Address all coefficients.</p>
<ul>
<li><strong>Answer:</strong></li>
<li>The average flipper length of the penguins on island Dream is 193.073 millimeters.</li>
<li>For the change from island Dream to island Biscoe, the flipper length of the penguins increases by 16.634 millimeters and is statistically significant.</li>
<li>For the change from island Dream to island Torgersen, the flipper length of the penguins decrease by 1.877 millimeters and it is not statistically significant.</li>
</ul></li>
</ul>
</section>
<section id="question-9-fit-a-logistic-regression" class="level2">
<h2 class="anchored" data-anchor-id="question-9-fit-a-logistic-regression">Question 9: Fit a logistic regression</h2>
<p>Apply a logistic regression. Include as many predictor variables as you’d like. Remember that your predicted outcome variable needs to be binary (or categorical with two levels).</p>
<p>Hint: You could use <code>sex</code> or create a binary variable of your own (e.g., Gentoo vs.&nbsp;non-Gentoo) to test your model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>logistic <span class="ot">&lt;-</span> <span class="fu">glm</span>(sex <span class="sc">~</span> flipper_length_mm, <span class="at">data =</span> penguins, <span class="at">family =</span> binomial)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logistic)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = sex ~ flipper_length_mm, family = binomial, data = penguins)

Coefficients:
                  Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)       -7.65801    1.68851  -4.535 5.75e-06 ***
flipper_length_mm  0.03822    0.00840   4.551 5.35e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 461.61  on 332  degrees of freedom
Residual deviance: 439.41  on 331  degrees of freedom
  (11 observations deleted due to missingness)
AIC: 443.41

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>What are your key takeaways from this model?</p>
<p><strong>Answer:</strong><br>
The intercept is -7.65801 and this is the log-odds of being a female when flipper length is zero. The coefficient flipper_length_mm represents the change in the log-odds of being a female for a one-unit increase in flipper length. Since the coefficient is positive, it suggests that <strong>as flipper length increases, the log-odds of being a female also increases</strong>.</p>
</section>
<section id="question-10-synthesize-the-information" class="level2">
<h2 class="anchored" data-anchor-id="question-10-synthesize-the-information">Question 10: Synthesize the information</h2>
<p>Imagine you’re a biologist studying penguin populations. Which predictors do you think are most important to measure or record in the field to predict flipper length? Why?</p>
<p><strong>Answer:</strong><br>
The predictors I believe are most important to record in order to predict flipper length are island, bill depth, species, and body mass. Doing some EDA, I found that these 4 variables played the biggest role and had the biggest change in output when it came to flipper length. Using a combination of these variables, the biologists should be able to more accurately predict flipper length.</p>
</section>
<section id="bonus-stepwise-regression" class="level2">
<h2 class="anchored" data-anchor-id="bonus-stepwise-regression">Bonus: Stepwise Regression</h2>
<p>Perform stepwise regression to find the best model for an outcome of your choice. You will likely encounter an error about missing values. Fixing that error and explaining your findings will earn you +2 extra credit. Show your work.</p>
<p>According to this stepwise regression, explain how the final model was selected.</p>
<p><strong>Answer:</strong><br>
(Write answer here)</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>